server:
  port: 8080

spring:
  application:
    name: book-shop
  datasource:
    url: jdbc:mysql://localhost:3306/book_shop_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem