server:
  port: ${PORT:8080}

spring:
  application:
    name: book-shop
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/book_shop_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
